routes/web.php
<?php


use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\IndexPageController;
use Telegram\Bot\Laravel\Facades\Telegram;
use \App\Http\Controllers\Profile\ProfileShowController;
use App\Http\Controllers\Services\Vk\CreateAccessTokenController as VkCreateAccessTokenController;
use App\Http\Controllers\Services\Instagram\CreateAccessTokenController as InstagramCreateAccessTokenController;

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/policy/', \App\Http\Controllers\PolicyPageController::class);

//Route::get('/telegramv2/',  \App\Http\Controllers\TelegramController::class);
/*Route::get('/telegram/', function (\Telegram\Bot\Api $telegram, \Illuminate\Support\Facades\Http $http){

    $response = Http::withOptions([
        'proxy' => 'http://24007289:1d5b5fb432ac7a6ca8d8e7f1bb7d8c47@149.154.167.40:443'
    ])
        ->asForm()
        ->get('https://api.telegram.org/bot6693072575:AAEeSTuMVSS_ZcIFSrIfX_xutN3zZTPfID4/messages.getHistory',
    [
        //'api_id' => 24007289,
        //'api_hash' => '1d5b5fb432ac7a6ca8d8e7f1bb7d8c47',
        //'bot_auth_token' => ''
        'peer' => '@interesting_blog'

    ])->json();

    dd($response);

   // $messageId = $response->getMessageId();

    dd($botId, $firstName, $username);
});
*/
require __DIR__.'/auth.php';



Route::middleware('auth')->group(function () {

    Route::get('/{page}', IndexPageController::class);
    Route::get('/', IndexPageController::class)->name('index');

    Route::get('/vk/access/',VkCreateAccessTokenController::class);
    Route::get('/instagram/access/',InstagramCreateAccessTokenController::class);

  //  Route::get('/profile', ProfileShowController::class)->name('profile.edit');
});

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/pages/policy.blade.php
<x-guest-layout>
    <h1 class="title title--h2">Политика конфиденциальности</h1>
    <p>
        Настоящая Политика конфиденциальности персональных данных (далее — Политика) действует в отношении всей информации, которую сайт <a href="/">www.soclick.ru</a>, на котором размещен текст этой Политики, может получить о Пользователе, и призвана разъяснить, какие данные собираются на сайте, как осуществляется их хранение и использование такой информации. В Политике приведена информация о том, какие меры принимаются для защиты информации, которая предоставляется через этот сайт.
    </p>
    <p>
        Политика вступает в силу с момента публикации на сайте. Администрация сайта оставляет за собой право вносить изменения в Политику при изменении внутренних процедур компании, в связи с чем мы рекомендуем вам периодически обращаться к действующей редакции Политики.
    </p>
    <p>
        Использование сервисов сайта означает безоговорочное согласие с настоящей Политикой и указанными в ней условиями обработки персональных данных; в случае несогласия с этими условиями Пользователь должен воздержаться от использования сервисов.
    </p>
    <h3>1. Термины</h3>
    <ul>
        <li>1.1 В настоящей Политике используются следующие термины:
            <ul>
                <li>1.1.1. Администрация сайта — уполномоченные сотрудники на управления сайтом <a href="/">www.soclick.ru</a>, действующие от его имени, которые организуют и (или) осуществляет обработку персональных данных, а также определяет цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными.</li>
                <li>1.1.2. Персональные данные — любая информация, относящаяся к прямо или косвенно к определенному или определяемому физическому лицу (субъекту персональных данных).</li>
                <li>1.1.3. Обработка персональных данных — любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных.</li>
                <li>1.1.4. Конфиденциальность персональных данных — обязательное для соблюдения Администрацией сайта требование не допускать их умышленного распространения без согласия субъекта персональных данных или наличия иного законного основания.</li>
                <li>1.1.5. Пользователь сайта (далее Пользователь) — лицо, имеющее доступ к сайту, посредством сети Интернет и использующее данный сайт для своих целей.</li>
                <li>1.1.6. Cookies — небольшой фрагмент данных, отправленный веб-сервером и хранимый на компьютере пользователя, который веб-клиент или веб-браузер каждый раз пересылает веб-серверу в HTTP-запросе при попытке открыть страницу соответствующего сайта.</li>
                <li>1.1.7. IP-адрес — уникальный сетевой адрес узла в компьютерной сети, построенной по протоколу IP.</li>
            </ul>
        </li>
    </ul>
    <h3>2. Общие положения</h3>
    <ul>
        <li>2.1. Использование Пользователем сайта <a href="/">www.soclick.ru</a> означает согласие с настоящей Политикой и условиями обработки персональных данных Пользователя.</li>
        <li>2.2. В случае несогласия с условиями Политики Пользователь должен прекратить использование сайта.</li>
        <li>2.3. Настоящая Политика применяется только к данному сайту <a href="/">www.soclick.ru</a>. Администрация сайта не контролирует и не несет ответственность за сайты третьих лиц, на которые Пользователь может перейти по ссылкам, доступным на данном сайте.</li>
        <li>2.4. Администрация сайта не проверяет достоверность персональных данных, предоставляемых Пользователем сайта.</li>
    </ul>
    <h3>3. Предмет Политики</h3>
    <ul>
        <li>3.1. Настоящая Политика устанавливает обязательства Администрации сайта по умышленному неразглашению персональных данных, которые Пользователь предоставляет по разнообразным запросам Администрации сайта (например, при оформлении заявки на консультацию и отправке файла для нее, при оформлении заявки на услугу и т.п).</li>
        <li>3.2. Персональные данные, разрешённые к обработке в рамках настоящей Политики, предоставляются Пользователем путём заполнения специальных форм на Сайте <a href="/">www.soclick.ru</a> и обычно включают в себя следующую информацию:
            <ul>
                <li>фамилию, имя, отчество Пользователя;</li>
                <li>контактный телефон Пользователя;</li>
                <li>адрес электронной почты (e-mail);</li>
            </ul>
        </li>
        <li>3.3. Администрация сайта также принимает усилия по защите Персональных данных, которые автоматически передаются в процессе посещения страниц сайта:
            <ul>
                <li>IP адрес;</li>
                <li>информация из cookies;</li>
                <li>информация о браузере (или иной программе, которая осуществляет доступ к сайту);</li>
                <li>время доступа;</li>
                <li>посещенные адреса страниц;</li>
                <li>реферер (адрес предыдущей страницы) и т.п.</li>
                <li>3.3.1. Отключение cookies может повлечь невозможность доступа к сайту.</li>
                <li>3.3.2. Сайт осуществляет сбор статистики об IP-адресах своих посетителей. Данная информация используется с целью выявления и решения технических проблем, для контроля корректности проводимых операций.</li>
            </ul>
        </li>
        <li>3.4. Любая иная персональная информация неоговоренная выше (используемые браузеры и операционные системы и т.д.) не подлежит умышленному разглашению, за исключением случаев, предусмотренных в п.п. 5.2. и 5.3. настоящей Политики.</li>
    </ul>
    <h3>4. Цели сбора персональной информации пользователя</h3>
    <ul>
        <li>4.1. Персональные данные Пользователя Администрация сайта может использовать в целях:
            <ul>
                <li>4.1.1. Идентификации Пользователя, заполнившего специальные формы на сайте, для оформления заявки на консультацию или услугу и (или) заключения Договора.</li>
                <li>4.1.2. Предоставления Пользователю доступа к персонализированным ресурсам сайта.</li>
                <li>4.1.3. Установления с Пользователем обратной связи, включая направление уведомлений, запросов, касающихся использования сайта, оказания услуг, предоставления консультаций, обработка запросов и заявок от Пользователя.</li>
                <li>4.1.4. Определения места нахождения Пользователя для обеспечения безопасности, предотвращения мошенничества.</li>
                <li>4.1.5. Подтверждения достоверности и полноты персональных данных, предоставленных Пользователем.</li>
                <li>4.1.6. Уведомления Пользователя сайта о состоянии заявки.</li>
                <li>4.1.7. Обработки и получения платежей, подтверждения налога или налоговых льгот, оспаривания платежа.</li>
                <li>4.1.8. Предоставления Пользователю эффективной клиентской и технической поддержки при возникновении проблем, связанных с использованием сайта.</li>
                <li>4.1.9. Предоставления Пользователю, обновлений услуг, специальных предложений, информации о ценах, новостной рассылки и иных сведений от имени сайта или от имени партнеров сайта.</li>
                <li>4.1.10. Осуществления рекламной деятельности с согласия Пользователя.</li>
            </ul>
        </li>
    </ul>
    <h3>5. Способы и сроки обработки персональной информации</h3>
    <ul>
        <li>5.1. Обработка персональных данных Пользователя осуществляется без ограничения срока, любым законным способом, в том числе в информационных системах персональных данных с использованием средств автоматизации или без использования таких средств.</li>
        <li>5.2. В ходе обработки с персональными данными будут совершены следующие действия: сбор; запись; систематизация; накопление; хранение; уточнение (обновление, изменение); извлечение; использование; блокирование; удаление; уничтожение.</li>
        <li>5.3. Пользователь соглашается с тем, что Администрация сайта вправе передавать персональные данные третьим лицам, в частности, курьерским службам, организациями почтовой связи, операторам электросвязи, исключительно в целях выполнения заявок Пользователя, оформленных на сайте <a href="/">www.soclick.ru</a>.</li>
        <li>5.4. Персональные данные Пользователя могут быть переданы уполномоченным органам государственной власти только по основаниям и в порядке, установленным действующим законодательством.</li>
    </ul>
    <h3>6. Обязательства сторон</h3>
    <ul>
        <li>6.1. Пользователь обязуется:
            <ul>
                <li>6.1.1. Предоставить корректную и правдивую информацию о персональных данных, необходимую для пользования сайтом.</li>
                <li>6.1.2. Обновить или дополнить предоставленную информацию о персональных данных в случае изменения данной информации.</li>
                <li>6.1.3. Принимать меры для защиты доступа к своим конфиденциальным данным, хранящимся на сайте.</li>
            </ul>
        </li>
        <li>6.2. Администрация сайта обязуется:
            <ul>
                <li>6.2.1. Использовать информацию исключительно для целей, указанных в п. 4 настоящей Политики конфиденциальности.</li>
                <li>6.2.2. Не разглашать персональных данных Пользователя, за исключением п.п. 5.3. и 5.4. настоящей Политики.</li>
                <li>6.2.3. Осуществить блокирование персональных данных, относящихся к соответствующему Пользователю, с момента обращения или запроса Пользователя или его законного представителя либо уполномоченного органа по защите прав субъектов персональных данных на период проверки, в случае выявления недостоверных персональных данных или неправомерных действий, а также при отзыве согласия Пользователя или истечении срока его действия.</li>
            </ul>
        </li>
    </ul>
    <h3>7. Ответственность сторон</h3>
    <ul>
        <li>7.1. Администрация сайта несёт ответственность за умышленное разглашение Персональных данных Пользователя в соответствии с действующим законодательством, за исключением случаев, предусмотренных п.п. 5.2., 5.3. и 7.2. настоящей Политики.</li>
        <li>7.2. В случае утраты или разглашения Персональных данных Администрация сайта не несёт ответственность, если данная конфиденциальная информация:
            <ul>
                <li>7.2.1. Стала публичным достоянием до её утраты или разглашения.</li>
                <li>7.2.2. Была получена от третьей стороны до момента её получения Администрацией сайта.</li>
                <li>7.2.3. Была получена третьими лицами путем несанкционированного доступа к файлам сайта.</li>
                <li>7.2.4. Была разглашена с согласия Пользователя.</li>
            </ul>
        </li>
        <li>7.3. Пользователь несет ответственность за правомерность, корректность и правдивость предоставленной Персональных данных в соответствии с действующим законодательством.</li>
    </ul>
    <h3>8. Разрешение споров</h3>
    <ul>
        <li>8.1. До обращения в суд с иском по спорам, возникающим из отношений между Пользователем сайта и Администрацией сайта, обязательным является предъявление претензии (письменного предложения о добровольном урегулировании спора).</li>
        <li>8.2. Получатель претензии в течение 30 календарных дней со дня получения претензии, письменно уведомляет заявителя претензии о результатах рассмотрения претензии.</li>
        <li>8.3. При не достижении соглашения спор будет передан на рассмотрение в судебный орган в соответствии с действующим законодательством.</li>
        <li>8.4. К настоящей Политике и отношениям между Пользователем и Администрацией сайта применяется действующее законодательство.</li>
    </ul>
    <h3>9. Дополнительные условия</h3>
    <ul>
        <li>9.1. Администрация сайта вправе вносить изменения в настоящую Политику конфиденциальности без согласия Пользователя.</li>
        <li>9.2. Новая Политика вступает в силу с момента ее размещения на Сайте <a href="/">www.soclick.ru</a>, если иное не предусмотрено новой редакцией Политики.</li>
    </ul>
    <h3>10. Доступ к вашим персональным данным</h3>
    <ul>
        <li>10.1. Пользователь может изменять и отзывать свои персональные данные, посредством направления соответствующего запроса с указанием в уведомлении своей фамилии, имени, почты, которые сообщали в числе своих данных по следующим адресам почты: <a href="mailto:pdmitrievich@gmail.com">pdmitrievich@gmail.com</a>, <a href="mailto:pdmitrievich@gmail.com">pdmitrievich@gmail.com</a>, по почтовому адресу: 109428, Москва, 2-я Институтская ул., д.6, стр. 64.</li>
        <li>10.2. В этом случае Администрация сайта будет блокировать персональные данные, с момента обращения или запроса на период проверки в случае выявления недостоверных персональных данных или неправомерных действий, а также принимать меры, чтобы удалить информацию из базы данных в установленные сроки.</li>
    </ul>
    <h3>11. Безопасность</h3>
    <p>
        На нашем сайте используются достаточные меры безопасности, направленные на предотвращение утраты, ненадлежащего использования, неуполномоченного доступа, раскрытия, изменения или повреждения информации, содержащей персональные данные.
    </p>
    <h3>12. Наши контакты</h3>
    <p>
        Пожалуйста, связывайтесь с нами, если у вас возникли какие-либо вопросы в отношении данной Политики или работы сайта в целом.
    </p>

    <p>
        E-mail: <a href="mailto:pdmitrievich@gmail.com">pdmitrievich@gmail.com</a>			</p>
    <p>
        <strong>Пользователь подтверждает, что ознакомлен со положениями Политики и безусловно принимает их.</strong>
    </p>
    </x-guest-layout>